---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3

   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: '!v3G@!4@Y'
       private: yes
       unsafe: yes

   tasks:
   - name: create a tenant
     aci_tenant: 
       tenant: am-tn
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"

   - name: create VRF
     aci_vrf: 
       vrf: am-vrf
       tenant: am-tn
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"

   - name: create a Bridge-Domain-webserver
     aci_bd: 
       tenant: am-tn
       bd: am-bd-webserver
       vrf: am-vrf
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       subnets:
         - name: 20.0.1.1
           mask: 24
           scope: public
   

   - name: create a Bridge-Domain-appserver
     aci_bd: 
       tenant: am-tn
       bd: am-bd-appserver
       vrf: am-vrf
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       subnets:
         - name: 10.0.1.1
           mask: 24
           scope: public


   - name: create a Bridge-Domain-data_centre
     aci_bd: 
       tenant: am-tn
       bd: am-bd-data_centre
       vrf: am-vrf
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       subnets:
         - name: 10.0.2.1
           mask: 24
           scope: public


   - name: create Application Profile
     aci_ap: 
       ap: am-ap
       tenant: am-tn
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
  
   - name: Add a new EPG
     aci_epg:
       tenant: am-tn
       ap: am-ap
       epg: am-epg
       description: "descrip"
       bd: am-bd
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"

#   - name: Add a Contract
#    aci_contract:
#      tenant: am-tn
#      ap: am-ap
#      epg: am-epg
#      description: "descrip"
#      bd: am-bd
#      host: "{{ inventory_hostname }}"
#      username: "{{ user }}"
#      password: "{{ pass }}"

