---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3

   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandboxapicdc.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       private: yes
       unsafe: yes

   tasks:
   - name: create a tenant
     aci_tenant: 
       tenant: am-tn
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"

   - name: create VRF
     aci_vrf: 
       vrf: am-vrf
       tenant: am-tn
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"

   - name: create a Bridge-Domain
     aci_bd: 
       tenant: am-tn
       bd: am-bd
       vrf: am-vrf
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"

   - name: create a Bridge-Domain Sub-net
     aci_bd_subnet: 
       tenant: am-tn
       bd: am-bd
       gateway: 200.1.1.1
       mask: 24
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"

   - name: create Application Profile
     aci_ap: 
       ap: am-ap
       tenant: am-tn
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
  
  - name: Add a new EPG
    aci_epg:
      tenant: am-tn
      ap: am-ap
      epg: am-epg
      description: "descrip"
      bd: am-bd
      host: "{{ inventory_hostname }}"
      username: "{{ user }}"
      password: "{{ pass }}"

