---
-  hosts: apic
   any_errors_fatal: true

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3

   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: '10.10.20.14'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'admin'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: 'QMTAXVNT'
       private: yes
       unsafe: yes


   tasks:
   - name: Authentication
     aci_rest:
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       use_ssl: yes
       validate_certs: false
       path: api/mo/uni.json
 
   - name: Remove a tenant
     aci_tenant: 
       tenant: am-tn
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       state: absent
