---
-  hosts: apic
   any_errors_fatal: true
   gather_facts: no

   vars:
     ansible_connection: local
     ansible_python_interpreter: /usr/bin/python3
     tn_name: 'am_tn'

     #ansible_connection: network_cli
     ansible_become: yes
     ansible_become_method: enable
     ansible_network_os: ios
     ansible_user: 'developer'
     ansible_ssh_pass: 'C1sco12345'
     ansible_port: 22
     netconf_port: 830

   vars_prompt:
     - name: "apic_ip"
       prompt: "Enter APIC IP"
       default: 'sandbox-iosxe-latest-1.cisco.com'
       private: no

     - name: "user"
       prompt: "Enter your APIC Username"
       default: 'developer'
       unsafe: yes

     - name: "pass"
       prompt: "Enter your APIC Password"
       default: 'C1sco12345'
       private: yes
       unsafe: yes

   tasks:
   - name: remove a tenant
     aci_tenant: 
       tenant: "{{ tn_name }}"
       host: "{{ inventory_hostname }}"
       username: "{{ user }}"
       password: "{{ pass }}"
       state: absent
